name: Profile Views Counter

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  profile-views:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Profile Views Counter
        uses: arturssmirnovs/github-profile-views-counter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
