name: GitHub Stats Update

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update GitHub Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: jstrieb/github-stats@v1
        with:
          TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: Pranavbm10
          INCLUDE_ALL_COMMITS: true
          COUNT_PRIVATE: true
